changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - Zenoixnoize
  categories:
    - title: Garfield-Latest-v6.0
      labels:
        - Semver-Major
        - breaking-change
    - title: Garfield-Latest-v6.0
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
